spring:
  mustache:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    enabled: true
    prefix: /pages/
    suffix: .mustache
---


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testwang?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wenqiang
  jpa:
    database-platform: MySQL5
    generate-ddl: true
    show-sql: true
  aop:
    auto: true
    proxy-target-class: true


